### ISSUE TITLE
How to specify nested config properties?

### ISSUE THREAD

**Issue by laymonk** [sl1pm4t/terraform-provider-lxd#120]
I am struggling to find the right hcl syntax for expressing a nested config for setting up a static network .. an equivalent to the lxd config like the following:
```
config:
  user.network-config: |
    version: 1
    config:
      - type: macvlan
        name: eth1
        subnets:
          - type: static
            ipv4: true
            address: 10.10.101.20
            netmask: 255.255.255.0
            gateway: 10.10.101.1
      - type: nameserver
        address: 10.10.10.254
```
* All variations I have tried have failed terraform's syntax .. 
* I have tried the following, and quite a few other variations
```
config {
   name = "user.network-config"
   version = "1"
   parameters {
      type = "macvlan"
      name = "eth1"
      subnets {
        blah
        blah
     }
  }
}
```
* In the above, I omitted the nameserver section ..

**Question**:  does this provider support this sort of nested config ?

**Comment by jtopjian** [comment]
@laymonk A heredoc string is probably the best choice here:

```hcl
config {
  user.network-config = <<-EOF
        version: 1
        config:
          - type: macvlan
            name: eth1
            subnets:
              - type: static
                ipv4: true
                address: 10.10.101.20
                netmask: 255.255.255.0
                gateway: 10.10.101.1
          - type: nameserver
            address: 10.10.10.254
  EOF
}
```

**Comment by laymonk** [comment]
Thanks for the quick response @jtopjian  .. but that has not worked.  

Using the heredoc generates the same hcl as suggested by [configformats](http://www.configformats.com/) for a yaml-to-hcl conversion :
```
"config" = {
  "user.network-config" = "version: 1\nconfig:\n  - type: physical\n    name: eth1\n    subnets:\n      - type: static\n        ipv4: true\n        address: 10.10.101.20\n        netmask: 255.255.255.0\n        gateway: 10.10.101.1\n        control: auto\n  - type: nameserver\n    address: 10.10.10.254"
}
```

I may have to consider using the file options to push static network config as an alternative  ..

**Comment by laymonk** [comment]
According to [lxd's cloud-init docs](https://github.com/lxc/lxd/blob/master/doc/cloud-init.md):
> Options available with such a template structure:
>
> * Use DHCP by default on your eth0 interface;
> * Set user.network_mode to link-local and configure networking by hand;
> * Seed cloud-init by defining user.network-config.

* DHCP is not an option for me
* I have gone with the last option, and it's not working, but I cannot say for certain this is an issue with this provider.  `Has anyone gotten a nested config like this to work with this provider?`
* Next, I will try setting user.network_mode to 'link-local' and pushing files to /etc/network/interfaces.d

**Comment by laymonk** [comment]
Just checked, and contrary to [lxd_container's docs](https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/docs/resources/lxd_container.md) .. for the file block:
* `content` is not optional, and `source` is not recognized as a valid config token
```
Error: lxd_container.ex3: "file.0.content": required field is not set
Error: lxd_container.ex3: file.0: invalid or unknown key: source
```
* Also seems like `file()` is not supported for `content` ..  using `content = file(/full/path/to/file)` , I get the following error (quoting the file path made no difference)
```
Error: Failed to load root config module: Error parsing /home/me/.terraform/example.tf: At 123:15: Unknown token: 123:15 IDENT file
```

So, back to using ansible to configure basic networking before full provisioning.  

By the way, this is a most useful provider .. thanks for putting it together.

**Comment by jtopjian** [comment]
A few quick notes here:

I don't think having a completely accurate HCL representation of the `network-config` structure is going to help. The value of the config setting is what matters. As long as the value is parsable YAML, that will get passed to cloud-init and cloud-init will then process it.

It's a little confusing here because YAML is structured data and embedding it in HCL feels weird, so it's only natural to want to convert YAML to HCL. But for this, stick with embedding either the YAML or the cloud-init syntax as a string.

It's _very_ possible the `network-config` setting is either being ignored or not working. I once tried for hours to get it to work on an OpenStack virtual machine until I realized that `network-config` might be ignored entirely depending on the host configuration.

To do a sanity check, try setting some arbitrary `user-data` (rather than `network-config`) and see if that gets executed correctly in cloud-init. You can also check under `/var/lib/cloud-or-something` (sorry, I don't have an off-hand example). That's where cloud-init will store the data (both user and network) given as input. If it exists under there, you know it was accepted but just not acted on.

I recall using `network-config` at some point or another in the past for LXD. I'm pretty sure I got it to work, but I'll have to dig it up. Let me know if you're still running into issues and I'll dig into this more. More times than not, I end up copying a static interfaces file to `/etc/network` just to get moving quickly.

Additionally, another option might be to configure your containers with a `device` of type `nic`. You should be able to specify a static IP that way. You'll have to use the LXD config [reference](https://github.com/lxc/lxd/blob/master/doc/containers.md#type-nic) for the exact properties to use, though. Again, if you get stuck, I can work up an example of this.

With regard to the `file` issues, the docs you're reading were from the master branch and were not applicable for the last release of this provider. @sl1pm4t _just_ released a new version of this provider which now correctly reflects what is in the docs. Sorry about that.

**Comment by laymonk** [comment]
@jtopjian, million thanks for the feedback .. 

Thanks too to @sl1pm4t for ensuring that the `file block` will work when next I try it .. 

* My containers are configured with `devices of type nic` but unfortunately ip settings here only seem to apply if one is using lxd's networking config .. 
* I am using macvlan and lxd's networking config is solely focused on bridges, or vxlan or gre tunnels (no macvlan support yet, it seems) .. 

I'm tied up on other tasks now, but will update terraform-provider-lxd and test the file block soon .. will also troubleshoot cloud-init issues as you suggested ..

Thanks again.

**Comment by MikeStankavich** [comment]
Maybe too late to do any good, but I have a HEREDOC working. 

```
  config {
    user.network-config = <<EOF
version: 1
config:
 - type: physical
   name: eth0
   subnets:
     - type: static
       ipv4: true
       address: 192.168.###.###
       netmask: 255.255.255.0
       gateway: 192.168.###.###
       control: auto


 - type: nameserver
   address: ['8.8.8.8', '8.8.4.4']
   search: ['mydomain.com']
EOF
  }
```
Or if you prefer v2, 
```
  config {
    # volatile.eth0.hwaddr = "02:00:00:nn:nn:nn"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
      - nnn.nnn.nnn.nnn/32
    gateway4: nnn.nnn.nnn.nnn
EOF
  }
```

The odd gateway and hwaddr bit are for OVH.

**Comment by jtopjian** [comment]
@MikeStankavich Thank you for this. I will update our documentation to add this as an example. If you'd like to submit a PR to our `/docs` directory, that would certainly be welcomed, too :)

**Comment by laymonk** [comment]
@MikeStankavich, much thanks for a heredoc that works .. 

@jtopjian, I settled for pushing files .. and couldn't find time to troubleshoot cloud-init issues (and it doesn't look like I need to any more) .. really appreciate your quick support ..

**Comment by jtopjian** [comment]
@laymonk sounds good and no problem at all. I am going to close this issue, but please let me know if you need any more help.

**Comment by a0s** [comment]
BTW, for now the right syntax is 
```
  config = {
    "user.network-config" = <<EOF
version: 2
```
