### ISSUE TITLE
make lxd_container_file forcibly recreate file (ignore missing file)

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#129]
I have the following `lxd_container_file` definition.
```
resource "lxd_container_file" "mylxd1_bootstrap" {
  remote         = "${var.lxdhost_name}"
  container_name = "${lxd_container.mylxd1.name}"
  content        = "${data.template_file.mylxd1_bootstrap.rendered}"
  target_file    = "/root/bootstrap.bash"
  uid            = 0
  gid            = 0
  mode           = "0755"
}
```

If I wanted to recreate `mylxd1`, I would taint `lxd_container.mylxd1`.
`lxd_container.mylxd1` gets recreated but the bootstrap files doesn't.

So, if I taint the `mylxd1_bootstrap` resource now, Terraform complains that the file doesn't already exist. ?? 

At this point I am stuck short of manually creating a file "/root/bootstrap.bash" inside the remote container.

So, my question is this, can `lxd_container_file` create a new file if it doesn't exist and treat a "missing file" as if it has to just re-create the file, rather than bailing.

```
Error: Error applying plan:

1 error(s) occurred:

* lxd_container_file.mylxd1_bootstrap (destroy): 1 error(s) occurred:

* lxd_container_file.mylxd1_bootstrap: unable to delete file mylxd1:/root/bootstrap.bash: Could not delete file /root/bootstrap.bash: not found
```

Regards,
Shantanu

**Comment by jtopjian** [comment]
@shantanugadgil Nice catch.

The best way of resolving this is to make sure all related resources are tainted. This will make Terraform recreate all resources upon the next apply.

However, I agree that this is a bug in general. For example, if a user deletes the file outside of Terraform, Terraform should recreate it.

#130 will fix this, but there's one caveat when used with tainting: Terraform won't notice the file is gone until after a _second_ apply:

```shell
$ terraform taint lxd_container.mylxd1
$ terraform apply
$ terraform apply
```

The reason is because tainting only marks the resource to be recreated. Technically the file still exists (the container is still running and the file is still there). It isn't until the container is recreated that the file is really gone. Again, tainting the file with the container will cause everything to be recreated upon the first apply.

Running two "apply"s is the closest possible to resolving this issue.

Let me know if you have any questions.

**Comment by shantanugadgil** [comment]
I will check this as soon as I can.

BTW, I did notice that users have asked for a 'taint dependency' in Terrform, which would solve this in a clen manner.

If it "just work" I am all OK with two apply commands.

I use a GNUmakefile to wrap my most needed Terraform cmds; plan, apply, show, refresh, etc.

**Comment by shantanugadgil** [comment]
@jtopjian 

This works now without "terraform apply" bailing with errors. :clap: 

Until Terraform itself gets a "taint dependency", I can live with manually tainting the other dependent resources (like the `null_resource` which executes this bootstrap script)

Thanks and Regards,
Shantanu

**Comment by jtopjian** [comment]
Glad it's working :)

> Should this issue be left open until a new official release?

Generally bugs are closed once they're fixed. I'd imagine we'll have a new release out soon, though.

**Comment by shantanugadgil** [comment]
Just to add, I added the trigger `mac_address`  to the corresponding `null_resource`.

This should take care of the `null_resource` forcibly executing when I taint and recreate the `lxd_container`.

```
triggers = {
  mylxd1_recreated = "${lxd_container.mylxd1.mac_address}"
}
```
