### ISSUE TITLE
file changes are not detected

### ISSUE THREAD

**Issue by johnlane** [sl1pm4t/terraform-provider-lxd#177]
I have a lxd_container that has a file block defined lke this
```
file {
  target_file = "/etc/some-file"
  source = "foo/some-file"
}
```
The file is uploaded with a new container but changes to the file are not detected by Terraform and it does not therefore upload  the changed file into the container. I have to do a destroy/create to get the file into the container.

I am using the precompiled 1.2.0 binary with Terraform 0.12.0.

**Comment by jtopjian** [comment]
@johnlane You might have better luck using `content` instead of `source`. However, keep in mind that the `file` argument is not meant to act as a configuration management system. It's best to use `file` to bootstrap a container and then offload the functionality to a proper configuration management system.

I'm going to close this issue, but please let me know if you have any other questions.
