### ISSUE TITLE
What is the correct way to add ssh public key to the image?

### ISSUE THREAD

**Issue by thepenguinthatwants** [sl1pm4t/terraform-provider-lxd#186]
I am trying to figure out how to add ssh public keys to the image so I can run ansible roles on the images?

Some images don't contain ssh, but command should be doable for them to install one. But how should the ssh public keys be added to the image?

If I try to add them by resource profiles, then does it always need a full path on properties?

I tried to add a public key as test but it didnt work.

```
resource "lxd_container_file" "ssh_keys" {
  container_name     = lxd_container.container1
  target_file        = "~/.ssh/id_rsa.pub"
  source             = "~/.ssh/id_rsa.pub"
  create_directories = true
}
```

**Comment by nihr43** [comment]
I don't know if there's a "right way", but I'll weigh in because I use this provider and ansible heavily.

Take a look at my repo [here](https://github.com/nihr43/iac-infra).

in the top level, I have `.tf` files defining logical deployments.  For the most part, they look like this:

```
resource "lxd_container" "haproxy-lxd" {
  count     = 2
  name      = "haproxy-lxd-${count.index}"
  image     = "alpine/stable"
  provisioner "local-exec" { command = "scripts/provision_alpine.sh ${self.name}" }
}
```

Notice the provisioner.  It points at [this script](https://github.com/nihr43/iac-infra/blob/master/scripts/provision_alpine.sh).  The relevant part starts at line `27`.  Here we use `lxc exec` to perform the minimal setup to run ansible.  Notice on line `43` I pull my public ssh key directly into authorized hosts.  Then on line `50`, I run `ansible-playbook` on only the new host, passed to the script as an argument.

This allows me full push-button deployments.

This setup has the following requirements:

- `dynamic dns hostname registration`: so "haproxy-lxd-0" is immediately resolvable as soon as the container boots.  I suppose you could find a way to do this all with static IPs, but that would require a few more steps.
- `hostname is already in inventory`: I'm not using a an inventory generator.  I haven't yet found one that suits my needs.

**Comment by jtopjian** [comment]
@nihr43's reply made me realize that I forgot about this issue. 

> I don't know if there's a "right way"

Correct. There is no official way of injecting SSH keys into the LXD containers. This allows the user/administrator to choose any method they want. 

@nihr43's method is the most popular: using some sort of provisioner (usually a local-exec which triggers an `lxc exec` or possibly even an `lxc file push`) to get the key inside the container.

Another method would be to build your own custom LXD images that have the key pre-installed. However, this means that if your key changes, you have to make new LXD images.

Personally, I use `lxc file push` to copy a bootstrap script to the container which will then configure the container from inside. This includes installation of any basic packages, installing SSH keys, etc. Once a basic configuration is done, something like Ansible or Puppet takes over.

But the important thing to note is that however you choose to inject your key, it is technically separate of this provider. You can use this provider to assist with key injection, but this provider does not (and should not) assist with doing any specific kind of provisioning.

**Comment by nihr43** [comment]
> You can use this provider to assist with key injection, but this provider does not (and should not) assist with doing any specific kind of provisioning.

Yup, thats what makes terraform such a great tool < The unix philosophy

**Comment by jtopjian** [comment]
@thepenguinthatwants 

> I tried to add a public key as test but it didnt work.

My apologies - I missed this part. It looks like there are two issues: you aren't referencing the container's name in `container_name` and using the `~` to expand the home directory (the `~` won't be expanded). In addition, you need to set a `mode` or else the file won't have any permissions on it.

A working example is:

```hcl
resource "lxd_container_file" "key" {
  container_name     = lxd_container.foo.name
  target_file        = "/root/.ssh/id_rsa.pub"
  source             = "/home/ubuntu/.ssh/id_rsa.pub"
  mode               = "0640"
  create_directories = true
}
```

I just verified that this works, but please let me know if you're still having problems.

**Comment by thepenguinthatwants** [comment]
> @thepenguinthatwants
> 
> > I tried to add a public key as test but it didnt work.
> 
> My apologies - I missed this part. It looks like there are two issues: you aren't referencing the container's name in `container_name` and using the `~` to expand the home directory (the `~` won't be expanded). In addition, you need to set a `mode` or else the file won't have any permissions on it.
> 
> A working example is:
> 
> ```terraform
> resource "lxd_container_file" "key" {
>   container_name     = lxd_container.foo.name
>   target_file        = "/root/.ssh/id_rsa.pub"
>   source             = "/home/ubuntu/.ssh/id_rsa.pub"
>   mode               = "0640"
>   create_directories = true
> }
> ```
> 
> I just verified that this works, but please let me know if you're still having problems.

Thanks!
I was just stumbling and not knowing that ~ wont expand etc. Thanks a lot guys!! Not feeling as lost as I were earlier.

**Comment by thepenguinthatwants** [comment]
> I don't know if there's a "right way", but I'll weigh in because I use this provider and ansible heavily.
> 
> Take a look at my repo [here](https://github.com/nihr43/iac-infra).
> 
> in the top level, I have `.tf` files defining logical deployments. For the most part, they look like this:
> 
> ```
> resource "lxd_container" "haproxy-lxd" {
>   count     = 2
>   name      = "haproxy-lxd-${count.index}"
>   image     = "alpine/stable"
>   provisioner "local-exec" { command = "scripts/provision_alpine.sh ${self.name}" }
> }
> ```
> 
> Notice the provisioner. It points at [this script](https://github.com/nihr43/iac-infra/blob/master/scripts/provision_alpine.sh). The relevant part starts at line `27`. Here we use `lxc exec` to perform the minimal setup required to run ansible. Notice on line `43` I pull my public ssh key directly into authorized hosts. Then on line `50`, I run `ansible-playbook` on only the new host, passed to the script as an argument.
> 
> This allows me full push-button deployments.
> 
> This setup has the following requirements:
> 
>     * `dynamic dns hostname registration`: so "haproxy-lxd-0" is immediately resolvable as soon as the container boots.  I suppose you could find a way to do this all with static IPs, but that would require a few more steps.
> 
>     * `hostname is already in inventory`: I'm not using a an inventory generator.  I haven't yet found one that suits my needs.

Thanks for the link of the repo. That Makefile itself is already so cool that it takes me time to digest those infos.

LXC playground is so nice especially for the speed of the deployments.

**Comment by jtopjian** [comment]
@thepenguinthatwants I'm going to close this issue, but please let me know if you have any additional questions or would like to see this issue re-opened.

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry for asking another noobish question. I've tried to add a key to the container but so far being stuck with this.
```
resource "lxd_container" "container1" {
  name     = "ubuntu1804"
  image = "ubuntu:18.04"
  ephemeral = false
  profiles = ["default"]

}

resource "lxd_container_file" "key" {
  container_name     = lxd_container.container1
  target_file        = "/root/.ssh/id_rsa.pub"
  source             = "/home/mike/.ssh/id_rsa.pub"
  mode               = "0640"
  create_directories = true
}
```
  Error: Incorrect attribute value type. Quite sure its just a simple mistake but cant figure out what.

**Comment by thepenguinthatwants** [comment]
Hi guys!

Thanks for helping.

I managed to get the key to authorized_keys file, but for some reasons I still cant ssh in.

```
resource "lxd_container_file" "container1" {
  container_name     = lxd_container.container1.name
  target_file        = "/root/.ssh/authorized_keys"
  source             = "/home/mike/.ssh/id_rsa.pub"
  mode               = "0640"
  create_directories = true
}
```

Trying to ssh in I get

` Permission denied (publickey).`

But the file is there in the server.

  image = "ubuntu:18.04"

**Comment by thepenguinthatwants** [comment]
Hi!

As many images doesnt have ssh server enabled normally and the guides says to manually prepare a base image that includes SSH. Is remote exec as it is known as bad idea to install ssh server for this matter?

Also after making own images are there good public hosting solutions for own custom lxc images so its easy to download using terraform configs?

**Comment by jtopjian** [comment]
> Is remote exec as it is known as bad idea to install ssh server for this matter?

Nope - not at all.

> Also after making own images are there good public hosting solutions for own custom lxc images so its easy to download using terraform configs?

Probably, but I don't have much experience with hosting public LXD image servers. I recommend checking out the official LXD community forums for ways of doing this.

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for the reply and sorry for continuing bothering.

I tried running this but remote exec was not expected?

Is there some special requirement with this?

```
resource "lxd_container" "container1" {
  name      = "ubuntu1804"
  image     = "ubuntu:18.04"
  ephemeral = false
  profiles  = ["default"]
  config = {
    "boot.autostart" = true
  }

    provisioner "remote-exec" {
      inline = [
        "apt update",
        "apt install ranger -y",
      ]
    }
  }
```

I get

`Blocks of type "provisioner" are not expected here.`

**Comment by jtopjian** [comment]
> Is there some special requirement with running remote exec?

Typically when using remote-exec provisioners, you need to be aware of the connection information: https://www.terraform.io/docs/provisioners/connection.html

Some resources are able to automatically detect certain attributes about a created resource (such as whether to use ssh, the IP address, etc) but you generally can't rely on this. You can see from the following error that an IP address was not detected automatically by Terraform

```
last error: SSH authentication failed (root@:22)
```

Therefore, you need to explicitly define the connection information.

In addition, instead of declaring provisioners inside the resources, it's more common to declare a `null_resource` and use that as the area for provisioners: https://www.terraform.io/docs/provisioners/null_resource.html

There are two reasons why this is recommended:

1. It decouples creating and provisioning so if the provisioning fails, Terraform won't mark the whole resource as having failed creation - just the provisioning part.

2. It sometimes takes more than one resource to fully define something you can connect to. For example:

```hcl
resource "lxd_container" "container1" {
  ...
}

resource "lxd_container_file" "ssh_key" {
  ...
}
```

You can't connect to the container with a `remote-exec` because the SSH key has not been added to the container yet. And you can't declare `lxd_container_file` before the container since that's illogical.

Therefore, you need to do something like:

```hcl
resource "lxd_container" "container1" {
  name     = "container1"
  image    = "ubuntu"
  profiles = ["default"]
}

resource "lxd_container_file" "ssh_key" {
  container_name     = lxd_container.container1.name
  target_file        = "/root/.ssh/authorized_keys"
  source             = "/home/ubuntu/.ssh/id_rsa.pub"
  mode               = "0640"
  create_directories = true
}

resource "null_resource" "provision" {
  depends_on = [
    lxd_container_file.ssh_key
  ]

  connection {
    type        = "ssh"
    user        = "root"
    private_key = file("/home/ubuntu/.ssh/id_rsa")
    host        = lxd_container.container1.ip_address
  }

  provisioner "local-exec" {
    command = "lxc exec ${lxd_container.container1.name} -- apt-get update -qq"
  }

  provisioner "local-exec" {
    command = "lxc exec ${lxd_container.container1.name} -- apt-get install -y openssh-server"
  }

  provisioner "remote-exec" {
    inline = [
      "hostname",
    ]
  }
}
```

Note that because `lxd_container_file` refers to the `lxd_container` resource in the `container_name` attribute, it creates an implicit dependency which will have Terraform first create the `lxd_container` and then the `lxd_container_file` resource.

In the `null_resource`, an explicit dependency is created by using `depends_on`. https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

If `depends_on` wasn't used, then the `null_resource` and `lxd_container_file` resources would have been executed in parallel instead of serially.

**Comment by thepenguinthatwants** [comment]
Thanks for the very comprehensive answer. I really like terraform to be able to use implicit dependency as it can in a way understand how to build the whole picture.

In lxd_profile.md  I managed to make a profile that could make containers to get shared folder to work. As this would prove to be very good development and testing enviroment.

```
  device {
    name = "shared"
    type = "disk"

    properties = {
      source = "/tmp"
      path   = "/tmp"
    }
  }
```

But I noticed that unless I use this command in the host the lxc image wont be able to write on the location

`chmod -R go+w`

Can this be somehow fixed by editing the terraform profile by uid and guid?

the whole folder has this rights if checked from the container
`drwxr-xr-x 2 nobody nogroup 4096`
