### ISSUE TITLE
Vendoring Dependencies?

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#22]
@sl1pm4t what are your thoughts on vendoring the dependent Go libraries? Most notably, `github.com/lxc/lxd`. 

(btw: I realize I'm spending a lot of time working on this. I'm on holiday for the rest of the year and this is sort of a vacation project. I take zero offence if things sit idle for weeks :smile: )

**Comment by sl1pm4t** [comment]
@jtopjian  Haha.. yeah you're making me feel bad for not working hard enough!
I'm particularly swamped at the moment, because I'm changing jobs soon and getting punished to finish some projects before I leave. :-)

In general, I think vendoring is a good idea. However, I'm not sure about vendoring *lxd* or *terraform*, because I think it's probably better to be aware if the builds are breaking against the latest code from those projects - especially Terraform which is very fast moving.

Have you seen issues / breaking changes from *lxd* ? 
I think I've only needed to fix about 2 breaking changes between this project and *lxd* in the past year. Of course, I was only using a fraction of the *lxd* API until recently, so the surface area was limited.

**Comment by jtopjian** [comment]
> I think it's probably better to be aware if the builds are breaking against the latest code from those projects - especially Terraform which is very fast moving.

This works for me, especially with Travis being able to run the acceptance tests. 

I haven't come across any breaking LXD changes, though I've only been working with it for the past two weeks :)
