### ISSUE TITLE
changing config values of lxd_container destroys and creates the container

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#50]
I am using the following versions:
Terraform v0.9.6
terraform-provider-lxd v0.9.5beta1

Changing the config values of an **lxd_container** resources causes the **lxd_container** to be destroyed and re-created while that is actually not needed.
I can perform the same changes using the lxc command line without having to recreate the lxd container.
Example:
```
# lxc config set mylxd  limits.cpu 2
# lxc config set mylxd  limits.cpu 4
```

Regards,
Shantanu

**Comment by jtopjian** [comment]
@shantanugadgil Please see https://github.com/sl1pm4t/terraform-provider-lxd/issues/21 for more information about this.

> Changing the config values of an lxd_container resources causes the lxd_container to be destroyed and re-created while that is actually not needed.

This is a very relative topic. What if an application running in the container crashed upon detecting the CPU count changed?

Since this topic is already being discussed in #21, I'm going to close this issue.
