### ISSUE TITLE
lxd_container resource does not honor "triggers"

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#52]
Terraform version: Terraform v0.9.6
terraform-provider-lxd: 0.9.5 beta1

```
# terraform plan
1 error(s) occurred:

* lxd_container.mylxd1: : invalid or unknown key: triggers
```

The relevant part of my resource definition:

```
 resource "lxd_container" "mylxd1" {
   triggers = {
     server_config_file = "${data.template_file.server_config.rendered}"
   }
```

Regards,
Shantanu

**Comment by jtopjian** [comment]
@shantanugadgil "triggers" are not a core Terraform feature. Some resources implement a schema attribute called "triggers" that is used to only detect changes:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/null/resource.go

Another example of this is "keepers":

https://github.com/hashicorp/terraform/blob/master/builtin/providers/random/resource_id.go

**Comment by shantanugadgil** [comment]
Hi @jtopjian thanks for the explanation.
I have **file** blocks inside the **lxd_container** which detect file changes, so that  solves _most_ of my need.

There is a last bit, where I need to restart a service inside the LXD when a file (and service) on the LXD host changes and restart.

Two different issues; maybe I'll try solve some other way.

I guess this issue can be closed then? Thanks!

**Comment by jtopjian** [comment]
Yeah, I would recommend looking into a `null_resource` for that type of management. A `null_resource` is an empty resource which can be used to house different provisioners and triggers.

Most other managed resources have the ability to have a `remote-exec` provisioner used, but since that's not possible with LXD containers, using a `local-exec` bundled inside a `null_resource` might be a good solution.
