### ISSUE TITLE
adding local-exec section doesn't cause a change in lxd_container

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#55]
Terraform version: Terraform v0.9.6
terraform-provider-lxd: 0.9.5 beta1

I have an **lxd_container** which has been successfully "applied".

I added the following block inside an **lxd_container**.
```
provisioner "local-exec" {
  command = "uname -a"
}
```

Now, when I execute "terraform plan", nothing happens. Terraform says:

> No changes. Infrastructure is up-to-date.

Not sure if this is a behavior due to TF or something to do with **terraform-provider-lxd**.

Thanks and Regards,
Shantanu

**Comment by jtopjian** [comment]
This is specific to Terraform. A provisioner is only run upon creation. It can optionally be run upon destruction if you specify `when = destroy`.

Using a `null_resource` with a trigger is probably the best way to go here.

This might be a helpful tip for designing: the fact that Terraform provisioners only run on creation and destruction point toward Terraform not being a full-fledged management tool. It's not uncommon to combine Terraform with Ansible or Puppet to provide day-to-day management of resources that cannot be easily recreated.

I'm going to close this issue since it's not specific to the LXD provider, but let me know if you have any questions.
