### ISSUE TITLE
separate 'mode' into 'file_mode' and 'dir_mode' for file block?

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#57]
Hi,
Would it be possible to separate the mode parameter into 'dir_mode' and 'file_mode'?

The use case is that typically one needs to create directories (sub-directories) as **0755** and the file with mode **0644** (or maybe 0600)

If I set the **mode** to **0600**, it gets applied for even the directories and sub-directories, thus making the file inaccessible for non-root users inside the lxd_container.

Regards,
Shantanu

**Comment by jtopjian** [comment]
The way `file` is implemented is exactly how the `lxc` command-line file copy action is implemented. So even if you use the command-line, it'll still create the directories with those permissions.

I agree that it can be awkward. I think the reason for this implementation is for two reasons:

1. It's simple
2. It shouldn't be mistaken as a provisioning tool.

The way I saw `file` used is to copy a provisioning / bootstrap script to a place like `/tmp` and then use `lxc exec` to trigger it.

I'm hesitant on adding a `directory` argument to `file`. Mostly because when creating the directories, it uses `mkdir -p`. I don't want to get into a bike shed discussion about creating 3 directories (`/usr/local/a/b/c/file.txt`) and wanting different permissions on `a` and `b`. Keeping `file` functionally the same as the LXD implementation might be best.

@sl1pm4t thoughts?

**Comment by shantanugadgil** [comment]
OK. I get what you're saying; it is mimicking `lxc file push`

```
# lxc file copy --help

lxc file push [-r|--recursive] [-p|--create-dirs] [--uid=UID] [--gid=GID] [--mode=MODE] <source path> [<source path>...] [<remote>:]<container>/<path>
    Push files into containers.
```

Indeed, I am looking at the "file" block as a mini-provisioning feature.
I think it satisfies my use case quite well already.
_The idea for the dir_mode and file_mode coming from my current usage of SaltStack, which I don't want to push inside my LXD containers._

The problem is this:
1. create a container
2. create directory inside container (using lxc exec or something???)
3. push a few files (certs, upstart configs, etc.) using file blocks.

Considering the above, how can I chain the directory creation _before_ file push ?!?
_I don't think there is a way to chain the "create directories" in-between the lxd creation and file push._

My idea is to deploy files with much more open perms (say 0755) and write a `null_resource` which `depends_on` the `lxd_container`, which can fixup the perms of the relevant files by using an `lxc exec`

**Comment by jtopjian** [comment]
Thinking out loud: what if you used a tool like [lxdfile](https://github.com/hverr/lxdfile) or [lxb](https://github.com/maryvilledev/lxb) to prepare images with this pre-provisioning already done?

> Considering the above, how can I chain the directory creation before file push ?!?
> I don't think there is a way to chain the "create directories" in-between the lxd creation and file push.

There's not, no. Not unless you build an image with your files/directories already existing or use the `file` block to deploy a shell script then trigger it with a `local-exec`.

**Comment by shantanugadgil** [comment]
Nice to know about lxdfile and lxb 👍 
I have already automated most of the bits where I create an LXD image with the packages required for my software (and the software itself).
Going one step further, I could even push the upstart scripts into the image (as their functionality stabilizes)
_the only reason they are outside is because the upstart scripts are still being developed._

I cannot bake in the SSL certs, though, which I will _have_ to push as a last step of deployment.

As I said earlier, I guess I'll make do with an alternative method.
It would have been _super-awesome_  to have this functionality in-built!
