### ISSUE TITLE
changes to file order

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#67]
As a suggestion, place lines 202-209 of resource_lxd_container.go to line 180 so that files are copied before container starts.  This will allow, among other things, placing files, such as rt_tables, and if-up.d files in place before networking kicks in.  Already changed my local copy.  If I was more familiar with git, I'd push/pull whatever for you to merge in.

**Comment by shantanugadgil** [comment]
if the change is small enough, you can just make online (in the webbrowser); github's online file editor will lead you through the steps. 😄 

otherwise:
fork the repo into your github account (so you have write access (push right) to it)
pull from your account onto your disk
make local changes; commit files (s), then push the file(s) back to your on github account
create pull request from your github account to the main account.

HTH 👍

**Comment by jtopjian** [comment]
Fixed by #76
